#

name: test-schedule

on:
  push:
  schedule:
    - cron: '29 15 * * *'


jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: dumy echo
        run: |
          echo "Dummy job is triggered ${{github.event}}"
